// qwriter.c -*- C -*-
//
// This file is part of the c3P language compiler. This project
// is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License
//
// This project is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// If not, see <http://www.gnu.org/licenses/>.
//

/*
 *	ISO C99 Standard: Q writer implementation for symt
 */

#include "../../../include/qwriter.h"

#include "../../../include/assertb.h"
#include "../../../include/arrcopy.h"

FILE* qw_new(char *filename)
{
	assertp(filename != NULL, "filename must be defined");

	FILE * file = fopen(filename, "w");
	assertf(file != NULL, "internal IO error for %s", filename);

	return file;
}

void qw_prepare(FILE *obj)
{
	assertp(obj != NULL, "object must be defined");
	fprintf(obj, "// ---------------------------------\n");
	fprintf(obj, "// Q file generated by c3p compiler\n");
	fprintf(obj, "// ---------------------------------\n");
	fprintf(obj, "#include \"../../include/Qlib.h\"\n");
	fprintf(obj, "BEGIN");
	fprintf(obj, "\n/**************** Start static data ****************/\nSTAT(0)");
	fprintf(obj, "\n\tSTR(0x11ff6,\"%%d\");\t// For integer format at show");
	fprintf(obj, "\n\tSTR(0x11ff2,\"%%f\");\t// For double format at show");
	fprintf(obj, "\n\tSTR(0x11ff0,\"%%c\");\t// For characer format at show");
	fprintf(obj, "\n\tSTR(0x11fee,\"%%s\");\t// For string format at show");
	fprintf(obj, "\n/**************** End static data ****************/");
	fprintf(obj, "\n/**************** Start code ****************/\nCODE(0)");
}

void qw_write_routine(FILE *obj, char *name, symt_label_t label, bool is_main)
{
	assertp(obj != NULL, "object must be defined");
	assertp(name != NULL, "name must be defined");

	if (is_main == true)
	{
		fprintf(obj, "\nL 0: /* Routine main */");
		fprintf(obj, "\n\tR6=R7;\t// Move current direction at R6");
	}
	else
		fprintf(obj, "\nL %d: /* Routine %s */", label, name);
}

void qw_write_close_routine(FILE *obj, char *name, bool is_main)
{
	assertp(obj != NULL, "object must be defined");
	assertp(name != NULL, "name must be defined");

	if (is_main != true)
	{
		fprintf(obj, "\n\tR6=R6-4;\t// Update R6 with previous call direction");
		fprintf(obj, "\n\tR0=I(R6);\t// Get the next label for last call");
		fprintf(obj, "\n\tGT(R0);\n/* End Routine %s */", name);
	}
}

void qw_write_begin_loop(FILE *obj, symt_label_t label)
{
    assertp(obj != NULL, "object must be defined");
    fprintf(obj, "\nL %d:\n\tR7=R7-4;\t// Begin Loop", label);
}

void qw_write_end_loop(FILE *obj, symt_label_t label, symt_label_t next_label)
{
    assertp(obj != NULL, "object must be defined");
    fprintf(obj, "\n\tGT(%d);\t// Repeat loop\nL %d:\n\tR7=R7+4;\t// End Loop", label, next_label);
}

void qw_write_new_label(FILE *obj, symt_label_t label)
{
    assertp(obj != NULL, "object must be defined");
    fprintf(obj, "\nL %d:", label);
}

void qw_write_goto(FILE *obj, symt_label_t label)
{
    assertp(obj != NULL, "object must be defined");
    fprintf(obj, "\n\tGT(%d); // Execute break o continue", label);
}

void qw_write_call(FILE *obj, symt_label_t rout_label, symt_label_t label)
{
    assertp(obj != NULL, "object must be defined");

	fprintf(obj, "\n\tI(R6)=%d;\t// Store current label at memory", label);
	fprintf(obj, "\n\tR6=R6+4;\t// Update R6 for future calls");
	fprintf(obj, "\n\tGT(%d);\t// Jump to the call routine", rout_label);
	fprintf(obj, "\nL %d:", label);
}

void qw_write_condition(FILE *obj, symt_label_t label)
{
    assertp(obj != NULL, "object must be defined");
	fprintf(obj, "\n\tIF(!R1) GT(%d);\t// Jump if condition is not true", label);
}

void qw_write_value_to_var(FILE *obj, symt_cons_t type, int q_direction, symt_value_t value)
{
	assertp(obj != NULL, "object must be defined");

	int value_int;
	double value_double;

	switch(type)
	{
		case CONS_INTEGER: case CONS_BOOL: case CONS_CHAR:
			value_int = *(int*)value;
			fprintf(obj, "\n\tI(0x%05x)=%d;\t// Store value to variable", q_direction, value_int);
		break;

		case CONS_DOUBLE:
			value_double = *(double*)value;
			fprintf(obj, "\n\tD(0x%05x)=%lf;\t// Store value to variable", q_direction, value_double);
		break;

		//case CONS_STR: break;
	}
}

void qw_write_var_to_reg(FILE *obj, symt_label_t num_reg, symt_cons_t type, int q_direction)
{
	assertp(obj != NULL, "object must be defined");

	int value_int;
	double value_double;

	switch(type)
	{
		case CONS_INTEGER: case CONS_BOOL: case CONS_CHAR:
			assertf(num_reg >= 0 && num_reg <= 7, "%d is not a valid register", num_reg);
			fprintf(obj, "\n\tR%d=I(0x%05x);\t// Load variable to register", num_reg, q_direction);
		break;

		case CONS_DOUBLE:
			assertf(num_reg >= 0 && num_reg <= 3, "%d is not a valid register", num_reg);
			fprintf(obj, "\n\tRR%d=D(0x%05x);\t// Load variable to register", num_reg, q_direction);
		break;

		//case CONS_STR: break;
	}
}

void qw_write_value_to_reg(FILE *obj, int num_reg, symt_cons_t type, symt_value_t value)
{
	assertp(obj != NULL, "object must be defined");

	int value_int;
	double value_double;

	switch(type)
	{
		case CONS_INTEGER: case CONS_BOOL: case CONS_CHAR:
			value_int = *(int*)value;
			assertf(num_reg >= 0 && num_reg <= 7, "%d is not a valid register", num_reg);
			fprintf(obj, "\n\tR%d=%d;\t// Set value to register", num_reg, value_int);
		break;

		case CONS_DOUBLE:
			value_double = *(double*)value;
			assertf(num_reg >= 0 && num_reg <= 3, "%d is not a valid register", num_reg);
			fprintf(obj, "\n\tRR%d=%f;\t// Set value to register", num_reg, value_double);
		break;

		//case CONS_STR: break;
	}
}

void qw_write_reg_to_var(FILE *obj, int num_reg, symt_cons_t type, int q_direction)
{
	assertp(obj != NULL, "object must be defined");

	switch(type)
	{
		case CONS_INTEGER: case CONS_BOOL: case CONS_CHAR:
			fprintf(obj, "\n\tI(0x%05x)=R%d;\t// Store result register at variable", q_direction, num_reg);
		break;

		case CONS_DOUBLE:
			fprintf(obj, "\n\tD(0x%05x)=RR%d;\t// Store result register at variable", q_direction, num_reg);
		break;

		//case CONS_STR: break;
	}
}

void qw_write_expr(FILE *obj, qw_op_t sign, symt_cons_t type, symt_label_t label)
{
	assertp(obj != NULL, "object must be defined");

	if (type == CONS_INTEGER || type == CONS_BOOL || type == CONS_CHAR)
	{
		switch(sign)
		{
			// Comparison
			case QW_LESS: fprintf(obj, "\n\tR%d=R%d<R%d;\t// Less operation", 1, 1, 2); 					break;
			case QW_GREATER: fprintf(obj, "\n\tR%d=R%d>R%d;\t// Greater operation", 1, 1, 2); 				break;
			case QW_LESS_THAN: fprintf(obj, "\n\tR%d=R%d<=R%d;\t// Less than operation", 1, 1, 2); 			break;
			case QW_GREATER_THAN: fprintf(obj, "\n\tR%d=R%d>=R%d;\t// Greater than operation", 1, 1, 2);    break;
			case QW_EQUAL: fprintf(obj, "\n\tR%d=R%d==R%d;\t// Equal operation", 1, 1, 2); 					break;
			case QW_NOT_EQUAL: fprintf(obj, "\n\tR%d=R%d!=R%d;\t// Not equal operation", 1, 1, 2); 			break;

			// Logical
			case QW_AND: fprintf(obj, "\n\tR%d=R%d!=R%d;\t// And operation", 1, 1, 2); 			break;
			case QW_OR: fprintf(obj, "\n\tR%d=R%d!=R%d;\t// Or operation", 1, 1, 2); 			break;
			case QW_NOT: fprintf(obj, "\n\tR%d=R%d!=R%d;\t// Not operation", 1, 1, 2); 			break;

			// Arithmetic
			case QW_ADD: fprintf(obj, "\n\tR%d=R%d+R%d;\t// Add operation", 1, 1, 2); 			break;
			case QW_SUB: fprintf(obj, "\n\tR%d=R%d-R%d;\t// Sub operation", 1, 1, 2); 			break;
			case QW_MULT: fprintf(obj, "\n\tR%d=R%d*R%d;\t// Mult operation", 1, 1, 2); 			break;
			case QW_DIV: fprintf(obj, "\n\tR%d=R%d/R%d;\t// Div operation", 1, 1, 2); 			break;
			case QW_POW: case QW_MOD:
				fprintf(obj, "\n\tR0=%d;\t// Set return label", label);
				fprintf(obj, "\n\tR3=%d;\t// Set operation for integers", 0);
				if (sign == QW_POW) fprintf(obj, "\n\tGT(pow_);\t// Pow operation");
				else fprintf(obj, "\n\tGT(mod_);\t// Mod operation");
				fprintf(obj, "\nL %d:", label);
			break;
		}
	}
	else if (type == CONS_DOUBLE)
	{
		switch(sign)
		{
			// Comparison
			case QW_LESS: fprintf(obj, "\n\tR%d=RR%d<RR%d;\t// Less operation", 1, 1, 2); 					break;
			case QW_GREATER: fprintf(obj, "\n\tR%d=RR%d>RR%d;\t// Greater operation", 1, 1, 2); 				break;
			case QW_LESS_THAN: fprintf(obj, "\n\tR%d=RR%d<=RR%d;\t// Less than operation", 1, 1, 2); 			break;
			case QW_GREATER_THAN: fprintf(obj, "\n\tR%d=RR%d>=RR%d;\t// Greater than operation", 1, 1, 2);    break;
			case QW_EQUAL: fprintf(obj, "\n\tR%d=RR%d==RR%d;\t// Equal operation", 1, 1, 2); 					break;
			case QW_NOT_EQUAL: fprintf(obj, "\n\tR%d=RR%d!=RR%d;\t// Not equal operation", 1, 1, 2); 			break;

			// Logical
			case QW_AND: fprintf(obj, "\n\tR%d=RR%d!=R%d;\t// And operation", 1, 1, 2); 			break;
			case QW_OR: fprintf(obj, "\n\tR%d=RR%d!=RR%d;\t// Or operation", 1, 1, 2); 			break;
			case QW_NOT: fprintf(obj, "\n\tR%d=RR%d!=RR%d;\t// Not operation", 1, 1, 2); 			break;

			// Arithmetic
			case QW_ADD: fprintf(obj, "\n\tRR%d=RR%d+RR%d;\t// Add operation", 1, 1, 2); 			break;
			case QW_SUB: fprintf(obj, "\n\tRR%d=RR%d-RR%d;\t// Sub operation", 1, 1, 2); 			break;
			case QW_MULT: fprintf(obj, "\n\tRR%d=RR%d*RR%d;\t// Mult operation", 1, 1, 2); 			break;
			case QW_DIV: fprintf(obj, "\n\tRR%d=RR%d/RR%d;\t// Div operation", 1, 1, 2); 			break;
			case QW_POW: case QW_MOD:
				fprintf(obj, "\n\tR0=%d;\t// Set return label", label);
				fprintf(obj, "\n\tR3=%d;\t// Set operation for integers", 1);
				if (sign == QW_POW) fprintf(obj, "\n\tGT(pow_);\t// Pow operation");
				else fprintf(obj, "\n\tGT(mod_);\t// Mod operation");
				fprintf(obj, "\nL %d:", label);
			break;
		}
	}
}

void qw_close(FILE * obj, symt_label_t label)
{
	assertp(obj != NULL, "object must be defined");
	fprintf(obj, "\nL %d:", label);
	fprintf(obj, "\n\tGT(-2);\t/* Exit program without errors */");
	fprintf(obj, "\n/**************** End code ****************/\nEND");
	fclose(obj);
}
